import Link from "next/link";
import { Archive,ArrowLeft,ChevronRight,Clock3,PackageCheck,RefreshCw,RotateCcw,ShieldCheck } from "lucide-react";
import { getLifecycleOverview } from "../server/lifecycle-overview";
import styles from "./lifecycle.module.css";

function nice(value){return String(value||"—").replaceAll("_"," ")}

export default async function LifecycleCenter(){
  const data=await getLifecycleOverview();
  return <main className={styles.page}>
    <header className={styles.top}><Link href="/"><ArrowLeft size={14}/>Dashboard</Link><div className={styles.brand}><img src="/subpar-logo.png" alt="Subpar Tuning"/><span><b>SUBPAR OS</b><small>LIFECYCLE CENTER</small></span></div><Link href="/go-live">Go Live <ChevronRight size={12}/></Link></header>
    <section className={styles.hero}><div><span>AFTER THE FINAL REVISION</span><h1>Close it cleanly. Reopen it without losing anything.</h1><p>Final QA, archive, follow-up and future retunes stay attached to the same customer and vehicle while each tune cycle gets its own historical boundary.</p></div><Archive size={34}/></section>
    <section className={styles.kpis}>{[["Ready to close",data.counts.readyToClose,PackageCheck],["Archived cycles",data.counts.archived,Archive],["Active retunes",data.counts.activeRetunes,RotateCcw],["Follow-ups",data.counts.followups,Clock3]].map(([label,value,Icon])=><article key={label}><Icon size={17}/><span>{label}</span><b>{value}</b></article>)}</section>
    <div className={styles.grid}>
      <section className={styles.panel}><header><div><span>NEEDS DOUG</span><h2>Ready for closeout</h2></div><PackageCheck size={18}/></header><div className={styles.rows}>{data.readyToClose.map(item=><Link href={`/closeout/${item.projectNumber}`} key={item.projectNumber}><div><b>{item.customer}</b><span>{item.vehicle}</span><small>{item.projectNumber} · Cycle {item.cycleNumber} · {item.platform} · {item.fuelTarget||"—"}</small></div><em>{item.nextAction||nice(item.status)}</em><ChevronRight size={13}/></Link>)}</div>{!data.readyToClose.length&&<div className={styles.empty}><ShieldCheck size={19}/><b>No tunes waiting for closeout.</b></div>}</section>
      <section className={styles.panel}><header><div><span>RETUNES</span><h2>Active new cycles</h2></div><RotateCcw size={18}/></header><div className={styles.rows}>{data.activeRetunes.map(item=><Link href={`/project/${item.projectNumber}`} key={`${item.projectNumber}-${item.cycleNumber}`}><div><b>{item.customer}</b><span>{item.vehicle}</span><small>{item.projectNumber} · Cycle {item.cycleNumber} · {nice(item.reason)}</small></div><em>{item.changeSummary||nice(item.status)}</em><ChevronRight size={13}/></Link>)}</div>{!data.activeRetunes.length&&<div className={styles.empty}><RefreshCw size={19}/><b>No active retunes.</b></div>}</section>
      <section className={`${styles.panel} ${styles.wide}`}><header><div><span>ARCHIVE</span><h2>Completed tune cycles</h2></div><Archive size={18}/></header><div className={styles.table}><div className={styles.tableHead}><span>Customer</span><span>Vehicle</span><span>Cycle</span><span>Final</span><span>Closed</span><span/></div>{data.archived.map(item=><div key={`${item.projectNumber}-${item.cycleNumber}`}><span><b>{item.customer}</b><small>{item.projectNumber}</small></span><span>{item.vehicle}</span><span>Cycle {item.cycleNumber}</span><span>Rev {item.finalRevisionNumber||"—"}</span><span>{item.closedAt?new Date(item.closedAt).toLocaleDateString():"—"}</span><Link href={`/closeout/${item.projectNumber}`}><ChevronRight size={13}/></Link></div>)}</div>{!data.archived.length&&<div className={styles.empty}><Archive size={19}/><b>No completed cycles yet.</b></div>}</section>
      <section className={`${styles.panel} ${styles.wide}`}><header><div><span>AFTERCARE</span><h2>Follow-up queue</h2></div><Clock3 size={18}/></header><div className={styles.table}><div className={styles.tableHead}><span>Customer</span><span>Vehicle</span><span>Status</span><span>Due</span><span>Project</span><span/></div>{data.followups.map(item=><div key={item.id}><span><b>{item.customer}</b><small>{item.lastError||"Post-closeout follow-up"}</small></span><span>{item.vehicle}</span><span>{nice(item.status)}</span><span>{item.dueAt?new Date(item.dueAt).toLocaleString():"—"}</span><span>{item.projectNumber}</span><Link href={`/closeout/${item.projectNumber}`}><ChevronRight size={13}/></Link></div>)}</div>{!data.followups.length&&<div className={styles.empty}><Clock3 size={19}/><b>No follow-ups waiting.</b></div>}<p className={styles.note}><ShieldCheck size={12}/>Scheduled automation only stages Gmail drafts. Provider send still requires the normal tuner approval/send boundary.</p></section>
    </div>
  </main>;
}
