"use client";

import { useMemo, useState } from "react";
import {
  LayoutDashboard,ListChecks,ShoppingBag,Activity,RefreshCw,MessageSquare,Users,Car,
  Calculator,Globe2,Settings,Search,Bell,Plus,ExternalLink,CheckCircle2,ChevronRight,
  Send,Mail,UploadCloud,Clock3,Gauge,Fuel,ArrowRight,CircleDollarSign,Database,Link2,
  ShieldCheck,FileText,Wrench,AlertTriangle
} from "lucide-react";

const jobs=[
{id:1,name:"Alex Rivera",email:"alex.rivera@gmail.com",vehicle:"2021 BMW M340i",engine:"B58TU",platform:"MHD",rev:"Rev 4",status:"Log Uploaded",priority:"High",last:"18m ago",fuel:"E40",order:"SP-1842",next:"Review 2 new logs",tone:"green"},
{id:2,name:"Mike Tremblay",email:"mike.tremblay@outlook.com",vehicle:"2019 BMW M2 Competition",engine:"S55",platform:"BM3",rev:"Rev 2",status:"Revision in Progress",priority:"High",last:"46m ago",fuel:"93",order:"SP-1839",next:"Finish Rev 2",tone:"red"},
{id:3,name:"Ryan Gallagher",email:"rgallagher@me.com",vehicle:"2022 BMW M3 Competition",engine:"S58",platform:"EcuTek",rev:"Rev 5",status:"Ready to Deliver",priority:"Med",last:"1h ago",fuel:"E50",order:"SP-1834",next:"Send customer update",tone:"purple"},
{id:4,name:"Sarah Chen",email:"s.chen.bmw@icloud.com",vehicle:"2020 Toyota Supra",engine:"B58",platform:"MHD",rev:"Rev 2",status:"Waiting on Customer",priority:"Med",last:"3h ago",fuel:"93",order:"SP-1830",next:"Waiting for pull",tone:"amber"},
{id:5,name:"Tyler Brooks",email:"tyler.brooks@gmail.com",vehicle:"2015 BMW 335i xDrive",engine:"N55",platform:"MHD",rev:"Rev 4",status:"Compatibility Review",priority:"Low",last:"5h ago",fuel:"E30",order:"SP-1827",next:"Review ROM details",tone:"blue"},
{id:6,name:"Carlos Mendez",email:"c.mendez.tuning@hotmail.com",vehicle:"2016 BMW M4",engine:"S55",platform:"BM3",rev:"Rev 1",status:"New Order",priority:"High",last:"Just now",fuel:"93",order:"SP-1846",next:"Send intake",tone:"amber"},
{id:7,name:"Jordan Patel",email:"jpatel@proton.me",vehicle:"2024 BMW M2",engine:"S58",platform:"EcuTek",rev:"Rev 1",status:"Vehicle Info Received",priority:"Med",last:"11m ago",fuel:"E50",order:"SP-1845",next:"Review intake",tone:"blue"},
{id:8,name:"Brandon Cole",email:"brandon@icloud.com",vehicle:"2023 BMW X3 M40i",engine:"B58TU",platform:"MHD",rev:"Rev 3",status:"Log Uploaded",priority:"High",last:"29m ago",fuel:"E35",order:"SP-1822",next:"Review HPFP trace",tone:"green"}
];

const nav=[
["dashboard","Dashboard",LayoutDashboard],["queue","Tune Queue",ListChecks],["orders","New Orders",ShoppingBag],
["logs","Datalog Reviews",Activity],["revisions","Tune Revisions",RefreshCw],["messages","Messages",MessageSquare],
["customers","Customers",Users],["garage","Vehicle Garage",Car],["calculator","E85 Calculator",Calculator],
["portal","Customer Portal",ExternalLink],["website","Website Redesign",Globe2],["integrations","Integrations",Settings]
];

const activities=[
[UploadCloud,"Alex Rivera uploaded 2 MHD logs","18m ago","green"],[Mail,"EcuTek log alert matched to Ryan Gallagher","31m ago","purple"],
[ShoppingBag,"Carlos Mendez purchased an S55 custom tune","Just now","amber"],[RefreshCw,"Mike Tremblay moved into Rev 2","46m ago","red"],
[MessageSquare,"Sarah Chen replied through Gmail","3h ago","blue"],[CheckCircle2,"Jordan Patel completed vehicle intake","11m ago","green"]
];

function Badge({children,tone="green"}){return <span className={`badge ${tone}`}>{children}</span>}

function Sidebar({active,setActive}){return <aside className="sidebar"><div className="brand"><img src="/subpar-logo.png" alt="Subpar Tuning"/><div><strong>SUBPAR OS</strong><span>TUNING DASHBOARD</span></div></div><nav>{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setActive(id)} className={active===id?"nav active":"nav"}><Icon size={15}/><span>{label}</span>{id==="queue"&&<em>18</em>}{id==="orders"&&<em>3</em>}{id==="logs"&&<em>7</em>}{id==="revisions"&&<em>4</em>}{id==="messages"&&<em>6</em>}</button>)}</nav><div className="sideBottom"><div className="user"><div className="avatar">DT</div><div><b>Doug Talmadge</b><span>Subpar Tuning</span></div><i/></div></div></aside>}

function Header({active,query,setQuery}){const label=nav.find(n=>n[0]===active)?.[1]||"Dashboard";return <header className="topbar"><div className="crumb"><b>SUBPAR OS</b><span>/</span>{label.toUpperCase()}</div><div className="topActions"><div className="search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customers, vehicles, emails, logs..."/></div><button className="iconBtn"><RefreshCw size={15}/></button><button className="iconBtn"><Bell size={15}/><i/></button></div></header>}

function PageHead({eyebrow,title,subtitle,action="Add",showAction=true}){return <div className="pageHead"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div>{showAction&&<button className="btn primary"><Plus size={13}/>{action}</button>}</div>}
function Stat({label,value,sub,tone="white",Icon}){return <div className="stat"><div className="statTop"><span>{label}</span>{Icon&&<Icon size={14}/>}</div><strong className={tone}>{value}</strong><small>{sub}</small></div>}

function QueueTable({query=""}){const [filter,setFilter]=useState("All");const rows=jobs.filter(j=>{const t=Object.values(j).join(" ").toLowerCase();const q=!query||t.includes(query.toLowerCase());const f=filter==="All"||(filter==="High"&&j.priority==="High")||filter===j.platform;return q&&f});return <section className="panel queuePanel"><div className="panelHead"><div><h3>Current Tune Queue</h3><p>Prioritized around the next action Doug needs to take.</p></div><div className="filters">{["All","High","MHD","BM3","EcuTek"].map(f=><button key={f} className={filter===f?"on":""} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><div className="tableWrap"><table><thead><tr><th>Customer</th><th>Vehicle</th><th>Platform</th><th>Rev</th><th>Status</th><th>Priority</th><th>Last</th><th></th></tr></thead><tbody>{rows.map(j=><tr key={j.id}><td><b>{j.name}</b><span>{j.email}</span></td><td><b className="normalWeight">{j.vehicle}</b><span>{j.engine} • {j.fuel}</span></td><td><Badge tone={j.platform==="MHD"?"green":j.platform==="BM3"?"blue":"purple"}>{j.platform}</Badge></td><td>{j.rev}</td><td><Badge tone={j.tone}>{j.status}</Badge><span>{j.next}</span></td><td><Badge tone={j.priority==="High"?"red":j.priority==="Med"?"amber":"gray"}>{j.priority}</Badge></td><td>{j.last}</td><td><button className="miniBtn"><ChevronRight size={14}/></button></td></tr>)}</tbody></table>{rows.length===0&&<div className="empty">No tunes match this filter.</div>}</div></section>}

function Dashboard({query}){return <div className="page"><div className="pageHead"><div><span className="eyebrow">SUBPAR TUNING • OPERATIONS</span><h1>Good evening, Doug.</h1><p>One place to run current tunes, review logs, manage revisions, and keep each car's history intact without replacing the tools you already use.</p></div><div className="headActions"><button className="btn secondary"><RefreshCw size={13}/>Sync activity</button><button className="btn primary"><Plus size={13}/>New tune</button></div></div><div className="stats"><Stat label="New Orders" value="3" sub="Wix purchases awaiting intake" tone="amber" Icon={ShoppingBag}/><Stat label="Logs Waiting" value="7" sub="MHD / BM3 / EcuTek" tone="green" Icon={Activity}/><Stat label="Revisions Due" value="4" sub="Needs Doug" tone="red" Icon={RefreshCw}/><Stat label="Ready to Deliver" value="2" sub="Customer-ready" tone="purple" Icon={Send}/><Stat label="Unread Messages" value="6" sub="Synced from Gmail" tone="blue" Icon={Mail}/><Stat label="Revenue This Month" value="$7,840" sub="Confirmed Wix orders" tone="green" Icon={CircleDollarSign}/><Stat label="Active Tunes" value="18" sub="Across 17 vehicles" Icon={Gauge}/><Stat label="Waiting on Customer" value="5" sub="Info / logs / waiver" tone="amber" Icon={Clock3}/></div><div className="dashGrid"><QueueTable query={query}/><div className="rightStack"><section className="panel"><div className="panelHead"><div><h3>Today's Activity</h3><p>Ingested from Doug's current stack.</p></div></div><div className="activityList">{activities.map(([Icon,text,time,tone])=><div className="activityRow" key={text}><div className={`activityIcon ${tone}`}><Icon size={13}/></div><div><b>{text}</b><span>{time}</span></div></div>)}</div></section><section className="panel"><div className="panelHead"><div><h3>Automated Intake</h3><p>Wix purchase → instructions → queue.</p></div></div><div className="steps">{[["1","Order received","Customer + product matched","done"],["2","Platform email sent","Correct MHD / BM3 / EcuTek steps","done"],["3","Vehicle intake","2 customers completing info","active"],["4","Tune queue","Doug sees next action",""]].map(([n,a,b,s])=><div className={`step ${s}`} key={n}><span>{n}</span><div><b>{a}</b><small>{b}</small></div></div>)}</div></section></div></div></div>}

function QueueView({query}){return <div className="page"><PageHead eyebrow="OPERATIONS" title="Tune Queue" subtitle="Every active project grouped by what happens next." action="New tune"/><div className="queueStats"><Stat label="Needs Doug" value="9" sub="Logs / revisions / deliveries" tone="green"/><Stat label="Waiting on Customer" value="5" sub="Info or new pull" tone="amber"/><Stat label="Ready to Deliver" value="2" sub="Maps ready to send" tone="purple"/></div><QueueTable query={query}/></div>}

function OrdersView(){const list=jobs.filter(j=>["New Order","Vehicle Info Received","Compatibility Review"].includes(j.status));return <div className="page"><PageHead eyebrow="WIX INTAKE" title="New Orders" subtitle="New purchases ready for intake, platform routing, and compatibility review." action="Manual order"/><div className="kanban"><section className="kanbanCol"><div className="kanbanTitle"><span>Needs Intake</span><Badge tone="amber">1</Badge></div>{list.filter(j=>j.status==="New Order").map(j=><OrderCard key={j.id} j={j}/>)}</section><section className="kanbanCol"><div className="kanbanTitle"><span>Intake Received</span><Badge tone="blue">1</Badge></div>{list.filter(j=>j.status==="Vehicle Info Received").map(j=><OrderCard key={j.id} j={j}/>)}</section><section className="kanbanCol"><div className="kanbanTitle"><span>Compatibility Review</span><Badge tone="purple">1</Badge></div>{list.filter(j=>j.status==="Compatibility Review").map(j=><OrderCard key={j.id} j={j}/>)}</section></div></div>}
function OrderCard({j}){return <article className="workCard"><div className="workTop"><div><b>{j.name}</b><span>{j.order}</span></div><Badge tone={j.platform==="MHD"?"green":j.platform==="BM3"?"blue":"purple"}>{j.platform}</Badge></div><h3>{j.vehicle}</h3><p>{j.engine} • {j.fuel}</p><div className="workMeta"><span><Clock3 size={12}/>{j.last}</span><span><Mail size={12}/>{j.email}</span></div><button className="wideBtn">Open intake <ChevronRight size={13}/></button></article>}

function LogsView(){const logs=jobs.filter(j=>j.status==="Log Uploaded");return <div className="page"><PageHead eyebrow="LOG INTELLIGENCE" title="Datalog Reviews" subtitle="MHD files, Datazap links, BM3 links and EcuTek alerts tied to the correct customer and order." action="Upload log"/><div className="logLayout"><section className="panel logInbox"><div className="panelHead"><div><h3>Review Queue</h3><p>Newest files first.</p></div><Badge tone="green">{logs.length} ready</Badge></div>{logs.map((j,i)=><div className="logRow" key={j.id}><div className="logIcon"><Activity size={16}/></div><div className="logMain"><div><b>{j.name}</b><span>{j.vehicle} • {j.platform} • {j.rev}</span></div><div className="logTags"><Badge tone="green">3rd gear</Badge><Badge tone="gray">CSV</Badge><Badge tone="gray">{j.fuel}</Badge></div></div><div className="logRight"><span>{i?"29m ago":"18m ago"}</span><button className="btn secondary">Review <ChevronRight size={12}/></button></div></div>)}</section><section className="panel logDetail"><div className="panelHead"><div><h3>Alex Rivera • Rev 4</h3><p>2021 M340i • B58TU • E40</p></div><button className="miniLink">Open Datazap <ExternalLink size={11}/></button></div><div className="metrics">{[["Boost Target","24.0 psi",82],["Boost Actual","24.3 psi",84],["Lambda","0.81",78],["Timing Corr.","-1.5°",34],["HPFP Min","2,570 psi",88],["IAT Peak","118°F",62]].map(([a,b,w])=><div className="metric" key={a}><span>{a}</span><b>{b}</b><div><i style={{width:`${w}%`}}/></div></div>)}</div><div className="insight"><CheckCircle2 size={15}/><div><b>Clean pull overall.</b><span>No throttle closure. Slight cylinder 4 correction around 5,700 RPM.</span></div></div></section></div></div>}

function RevisionsView(){return <div className="page"><PageHead eyebrow="CALIBRATION WORKFLOW" title="Tune Revisions" subtitle="Keep every revision, log set, customer note and delivery status attached to the same tune project." action="New revision"/><div className="revisionGrid">{jobs.slice(0,6).map(j=><article className="revisionCard" key={j.id}><div className="revisionTop"><div><span>{j.order}</span><h3>{j.name}</h3><p>{j.vehicle}</p></div><Badge tone={j.tone}>{j.rev}</Badge></div><div className="revProgress"><i style={{width:`${Math.min(95,30+j.id*9)}%`}}/></div><div className="revBottom"><div><span>Status</span><b>{j.status}</b></div><div><span>Next</span><b>{j.next}</b></div></div><button className="wideBtn">Open project <ChevronRight size={13}/></button></article>)}</div></div>}

function MessagesView(){return <div className="page"><PageHead eyebrow="COMMUNICATION" title="Messages" subtitle="Gmail conversations tied to the right customer, vehicle, and tune." action="New message"/><div className="messageShell"><section className="threadList">{jobs.slice(0,6).map((j,i)=><button key={j.id} className={i===0?"thread activeThread":"thread"}><div className="avatar small">{j.name.split(" ").map(x=>x[0]).join("")}</div><div><b>{j.name}</b><span>{i===0?"Sent new log — let me know how it looks":"Customer thread synced from Gmail"}</span></div><em>{j.last}</em></button>)}</section><section className="conversation"><div className="conversationHead"><div><b>Alex Rivera</b><span>2021 M340i • SP-1842 • MHD Rev 4</span></div><Badge tone="green">Active tune</Badge></div><div className="messages"><div className="bubble incoming"><span>Alex • 8:42 PM</span><p>Just uploaded two new logs. Car feels much smoother on this revision.</p></div><div className="bubble outgoing"><span>Doug • 8:48 PM</span><p>Perfect. I have them attached to your tune now. I’ll review the pull and get back to you with the next step.</p></div></div><div className="composer"><input placeholder="Reply through Gmail..."/><button className="btn primary"><Send size={13}/>Send</button></div></section></div></div>}

function CustomerGrid({garage=false,query=""}){const list=jobs.filter(j=>!query||Object.values(j).join(" ").toLowerCase().includes(query.toLowerCase()));return <div className="cardsGrid">{list.map(j=><article className="customerCard" key={j.id}><div className="cardTop"><div className="avatar small">{j.name.split(" ").map(x=>x[0]).join("")}</div><Badge tone={j.platform==="MHD"?"green":j.platform==="BM3"?"blue":"purple"}>{j.platform}</Badge></div><h3>{garage?j.vehicle:j.name}</h3><p>{garage?j.name:j.vehicle}</p><div className="cardMeta"><span>{j.engine}</span><span>{j.fuel}</span><span>{j.rev}</span></div><div className="cardAction"><div><small>{j.order}</small><b>{j.status}</b></div><ChevronRight size={15}/></div></article>)}</div>}
function CustomersView({query}){return <div className="page"><PageHead eyebrow="CUSTOMER CRM" title="Customers" subtitle="Customer, order, vehicle, tune, log and communication history in one profile." action="Add customer"/><CustomerGrid query={query}/></div>}
function GarageView({query}){return <div className="page"><PageHead eyebrow="VEHICLE HISTORY" title="Vehicle Garage" subtitle="Every car Doug has tuned with engine, platform, fuel, revisions, and history preserved." action="Add vehicle"/><CustomerGrid garage query={query}/></div>}

function CalculatorView(){const presets={"M340i G20":15.6,"M240i G42":13.7,"M3/M4 G8X":15.6,"M2 G87":13.7,"X3 M40i":17.2,"X3M":17.2,"Supra A90/A91":13.7};const [preset,setPreset]=useState("M340i G20"),[tank,setTank]=useState(15.6),[current,setCurrent]=useState(5),[currentE,setCurrentE]=useState(10),[e85,setE85]=useState(78),[target,setTarget]=useState(40);const add=Math.max(0,tank-current),denom=Math.max(1,e85-10),eth=Math.max(0,Math.min(add,((target*tank)-(currentE*current)-(10*add))/denom)),pump=Math.max(0,add-eth);return <div className="page"><PageHead eyebrow="CUSTOMER TOOL" title="E85 Blend Calculator" subtitle="BMW-focused ethanol blending built directly into the Subpar customer experience." showAction={false}/><div className="calculatorGrid"><section className="panel calcCard"><div className="calcHead"><Fuel size={18}/><div><h3>Vehicle + Fuel</h3><p>Set the car and current tank state.</p></div></div><label><span>Vehicle preset</span><select value={preset} onChange={e=>{setPreset(e.target.value);setTank(presets[e.target.value])}}>{Object.keys(presets).map(p=><option key={p}>{p}</option>)}</select></label>{[["Tank Capacity (gal)",tank,setTank],["Fuel Currently in Tank (gal)",current,setCurrent],["Current Ethanol %",currentE,setCurrentE],["Actual E85 Ethanol %",e85,setE85],["Target Ethanol %",target,setTarget]].map(([l,v,s])=><label key={l}><span>{l}</span><input type="number" value={v} onChange={e=>s(Number(e.target.value))}/></label>)}</section><section className="panel resultCard"><span className="eyebrow">TARGET BLEND</span><strong>E{target}</strong><p>{preset} • {tank.toFixed(1)} gal tank</p><div className="resultRows"><div><span>Add E85</span><b>{eth.toFixed(2)} gal</b></div><div><span>Add pump gas</span><b>{pump.toFixed(2)} gal</b></div><div><span>Total added</span><b>{add.toFixed(2)} gal</b></div></div><div className="mixBar"><i style={{width:`${add?eth/add*100:0}%`}}/><span/></div><div className="note"><AlertTriangle size={14}/>Verify actual ethanol content before mixing. Pump gas is assumed to be E10.</div></section></div></div>}

function PortalView(){return <div className="page"><PageHead eyebrow="CUSTOMER EXPERIENCE" title="Customer Portal" subtitle="A consistent customer experience regardless of whether the tune runs through MHD, bootmod3, or EcuTek." showAction={false}/><div className="portalShell"><div className="portalTop"><div className="portalBrand"><img src="/subpar-logo.png"/><div><b>SUBPAR TUNING</b><span>Customer Portal</span></div></div><div className="portalUser"><div className="avatar small">AR</div><div><b>Alex Rivera</b><span>2021 BMW M340i</span></div></div></div><div className="portalGrid"><section className="portalHero"><Badge tone="green">Revision 4 active</Badge><h2>Your custom tune is in review.</h2><p>Doug received your latest logs 18 minutes ago. You don’t need to send anything else right now.</p><div className="timeline">{[["Order","Complete","done"],["Vehicle intake","Complete","done"],["Base map","Delivered","done"],["Rev 4 logs","Under review","active"],["Next revision","Pending",""]].map(([a,b,s])=><div className={s} key={a}><i/><span><b>{a}</b><small>{b}</small></span></div>)}</div></section><section className="portalSide"><div className="portalCard"><span>NEXT STEP</span><h3>Doug is reviewing your logs</h3><p>You’ll get a message when the next revision or instruction is ready.</p></div><div className="portalCard"><span>YOUR CAR</span><h3>2021 BMW M340i</h3><p>B58TU • MHD • E40 • Rev 4</p></div><div className="portalCard"><span>FILES</span><div className="fileLine"><FileText size={14}/>Subpar_B58TU_E40_Rev4.bin <Badge tone="green">Current</Badge></div></div></section></div></div></div>}

function WebsiteView(){return <div className="page"><PageHead eyebrow="WEBSITE REDESIGN" title="SubparTuning.com Concept" subtitle="Keep Wix commerce underneath, but make the customer-facing site feel like the same premium product as Subpar OS." showAction={false}/><section className="siteMock"><div className="siteTop"><div className="siteBrand"><img src="/subpar-logo.png"/><div><b>SUBPAR TUNING</b><span>Custom Calibration • Remote Tuning</span></div></div><div className="siteNav"><span>Custom Tuning</span><span>Platforms</span><span>Revisions</span><span>About</span><button>Customer Portal</button></div></div><div className="siteHero"><div><span className="eyebrow">BMW • TOYOTA SUPRA • REMOTE CUSTOM TUNING</span><h2>Built around the car.<br/><em>Backed by the data.</em></h2><p>Custom calibration across MHD, bootmod3 and EcuTek with a cleaner purchase, intake, log, and revision process.</p><div className="siteBtns"><button className="btn primary">Shop Custom Tunes <ArrowRight size={13}/></button><button className="btn secondary">Customer Portal</button></div></div><div className="siteLogoStage"><div/><img src="/subpar-logo.png"/></div></div><div className="siteSection"><span className="eyebrow">POPULAR CALIBRATIONS</span><h3>Find your platform.</h3><div className="products">{[["S58","M2 / M3 / M4","$850"],["B58 / B58TU","M240i / M340i / Supra","$650"],["S55","F8X M2C / M3 / M4","$750"],["N55","E / F chassis","From $550"]].map(([e,n,p])=><article className="productCard" key={e}><div className="productIcon"><Gauge size={17}/></div><span>{e}</span><h4>{n}</h4><p>Custom remote calibration with organized intake, revisions and log workflow.</p><b>{p}</b><div><Badge>MHD</Badge><Badge tone="blue">BM3</Badge></div></article>)}</div></div></section></div>}

function IntegrationsView(){const items=[["Wix",ShoppingBag,"Orders, products, customers and payment status.","Foundation"],["Gmail",Mail,"Sync customer threads, send intake, ingest EcuTek alerts.","Foundation"],["MHD",Gauge,"Primary platform: revisions, logs and Datazap workflow.","Deep integration"],["bootmod3",Link2,"Track tune requests, shared logs and status without replacing BM3.","Ingestion"],["EcuTek",Activity,"Match emailed log alerts and ECU Connect activity to orders.","Ingestion"],["Datazap",Database,"Attach shared log URLs and normalized review data.","Log layer"]];return <div className="page"><PageHead eyebrow="CONNECTED SYSTEMS" title="Integrations" subtitle="Subpar OS is the organization layer — not a replacement for the tools Doug already uses." showAction={false}/><div className="settingsGrid">{items.map(([a,Icon,b,c])=><section className="panel settingCard" key={a}><div className="settingTop"><div className="settingIcon"><Icon size={17}/></div><Badge tone={a==="Wix"||a==="Gmail"?"green":"gray"}>{c}</Badge></div><h3>{a}</h3><p>{b}</p><button className="btn secondary">Configure <ChevronRight size={12}/></button></section>)}</div><div className="securityNote"><ShieldCheck size={18}/><div><b>Live ingestion stays off until the corrected NDA is signed.</b><span>UI, schema and demo workflows can keep moving with synthetic data meanwhile.</span></div></div></div>}

export default function Home(){const [active,setActive]=useState("dashboard"),[query,setQuery]=useState("");const content=useMemo(()=>{switch(active){case"dashboard":return <Dashboard query={query}/>;case"queue":return <QueueView query={query}/>;case"orders":return <OrdersView/>;case"logs":return <LogsView/>;case"revisions":return <RevisionsView/>;case"messages":return <MessagesView/>;case"customers":return <CustomersView query={query}/>;case"garage":return <GarageView query={query}/>;case"calculator":return <CalculatorView/>;case"portal":return <PortalView/>;case"website":return <WebsiteView/>;case"integrations":return <IntegrationsView/>;default:return <Dashboard query={query}/>}},[active,query]);return <div className="shell"><Sidebar active={active} setActive={setActive}/><main className="main"><Header active={active} query={query} setQuery={setQuery}/>{content}</main></div>}
